// Code generated by "stringer -type=JobStatus -output=job_status_string.go"; DO NOT EDIT.

package queue

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-0]
	_ = x[Running-1]
	_ = x[Done-2]
}

const _JobStatus_name = "IdleRunningDone"

var _JobStatus_index = [...]uint8{0, 4, 11, 15}

func (i JobStatus) String() string {
	if i < 0 || i >= JobStatus(len(_JobStatus_index)-1) {
		return "JobStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
