// Code generated by "stringer -type=DataSourceStatus -output=data_source_status_string.go"; DO NOT EDIT.

package datasources

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Initial-0]
	_ = x[Running-1]
	_ = x[Stopping-2]
	_ = x[Stopped-3]
	_ = x[Finished-4]
	_ = x[Disabled-5]
	_ = x[Error-6]
}

const _DataSourceStatus_name = "InitialRunningStoppingStoppedFinishedDisabledError"

var _DataSourceStatus_index = [...]uint8{0, 7, 14, 22, 29, 37, 45, 50}

func (i DataSourceStatus) String() string {
	if i < 0 || i >= DataSourceStatus(len(_DataSourceStatus_index)-1) {
		return "DataSourceStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataSourceStatus_name[_DataSourceStatus_index[i]:_DataSourceStatus_index[i+1]]
}
