// Package datasources Code generated by generator, DO NOT EDIT.
package datasources

var Workers = []string{
	"CallbackWorker",
	"HttpRequestWorker",
	"HttpServerWorker",
	"RandomValueWorker",
	"SqlWorker",
}

var DataPoints = []string{
	"HttpRequestDataPoint",
	"HttpServerDataPoint",
	"RandomValueDataPoint",
	"SqlDataPoint",
}
