// Package datasources Code generated by generator, DO NOT EDIT.
package datasources

var WorkerTypes = []string{
	"Callback",
	"HttpRequest",
	"HttpServer",
	"RandomValue",
	"Sql",
}

var DataSourceTypes = []string{
	"Sql",
	"HttpRequest",
	"HttpServer",
	"RandomValue",
}
