// Code generated by "stringer -type=ViewType -output=view_type_string.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimeSeriesViewType-0]
	_ = x[GraphicalViewType-1]
}

const _ViewType_name = "TimeSeriesViewTypeGraphicalViewType"

var _ViewType_index = [...]uint8{0, 18, 35}

func (i ViewType) String() string {
	if i < 0 || i >= ViewType(len(_ViewType_index)-1) {
		return "ViewType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewType_name[_ViewType_index[i]:_ViewType_index[i+1]]
}
