name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest, macOS-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Test
        run:
          mkdir ./pkg/server/public
          go test ./...

  version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Bump version
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v5.6
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}