on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Master
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run:
          mkdir ./pkg/server/public
          go test ./...

  Version:
    setup:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Bump version
          if: github.ref == 'refs/heads/master'
          uses: mathieudutour/github-tag-action@v5.6
          id: bump
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}