on:
  pull_request:
    branches:
      - release
name: Release
jobs:
  test:
    runs-on: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - run:
          mkdir ./pkg/server/public
          go test ./...

  Version:
    setup:
      runs-on: [ ubuntu-latest, macos-latest ]
      needs: test
      steps:
        - uses: actions/setup-go@v3
          name: Setup Go
          with:
            go-version: 1.18.x

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Build
        - run:
            make api
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: ./api