name: Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest, macOS-12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run:
          mkdir ./pkg/server/public
          go test ./...

  build:
    needs: test
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        name: Setup Go
        with:
          go-version: 1.18.x

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run:
          make api

  version:
    runs-on: [ ubuntu-latest, macos-latest ]
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./api